set -g mouse on

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_DATA_HOME/tmux/plugins/"

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @vim_navigator_mapping_prev ""

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
